from __future__ import annotations


LORE_TOP_K = 3
MEMORY_TOP_K = 4
RELATIONSHIP_TOP_K = 2

LORE_THRESHOLD = 1.4
MEMORY_THRESHOLD = 1.5
RELATIONSHIP_THRESHOLD = 1.2

IMPORTANT_MEMORY_KEYWORDS = (
    "important",
    "remember",
    "promise",
    "decide",
    "plan",
    "기억",
    "중요",
    "약속",
    "결정",
    "계획",
)

LORE_TOPIC_EXACT_BOOST = 2.0
LORE_ALIAS_MATCH_BOOST = 1.3
LORE_TOPIC_HINT_BOOST = 1.2
LORE_WORLD_MATCH_BOOST = 0.6
LORE_PRIORITY_BOOST_PER_STEP = 0.08
LORE_MAX_PRIORITY_STEPS = 10
LORE_UNRELATED_PENALTY = -1.6

MEMORY_IMPORTANCE_BOOST = 0.7
MEMORY_RECENCY_BOOST_PER_STEP = 0.2
MEMORY_RECENCY_BOOST_CAP = 0.8
MEMORY_ACTIVE_SPEAKER_BOOST = 1.4
MEMORY_PARTICIPANT_BOOST = 0.5
MEMORY_SCENE_MATCH_BOOST = 0.7
MEMORY_STALE_PENALTY = -1.0

RELATIONSHIP_SOURCE_TARGET_EXACT_BOOST = 1.8
RELATIONSHIP_PARTICIPANT_PRESENCE_BOOST = 0.8
RELATIONSHIP_TONE_SCENE_RELEVANCE_BOOST = 0.6
RELATIONSHIP_UNRELATED_PENALTY = -1.1
